# Generated by Django 4.0.5 on 2022-07-12 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glass',
            old_name='glass_name',
            new_name='name',
        ),
    ]
